### PR TITLE
Prepare to release v1.0.1

### PR DESCRIPTION
**Pull request by lumaxis**
I would love to see the fixes I made in #117 be released, therefore here's an attempt at helping to prepare a release to help ease the process 👍

### CODE REVIEW

**Comment by whitlockjc** [comment]
Thanks for your help.  I'll try to get this out ASAP.

**Comment by lumaxis** [comment]
@whitlockjc Ping? 🙂

**Comment by gordey4doronin** [comment]
It would be cool to also include circular refs fix (as soon as `json-refs` new release is ready including recent @whitlockjc commit https://github.com/whitlockjc/json-refs/commit/f088335b4925a88e7b5baad7347b68e2fbe0142d).

I have this, but not sure if it should be hardcoded or configurable?
https://github.com/gordey4doronin/sway/commit/f0a064fb7bb20a3db9e2c5ad358eb2aa44fd7b89

**Comment by whitlockjc** [comment]
The next release of `sway` will upgrade to `json-refs@v3.0.0` when it is released.  The `json-refs` release should happen within the next day or so.

**Comment by whitlockjc** [comment]
As for using `options.resolveCirculars` _(sorry for the rename, it was `options.allowCirculars`)_, I've not verified that `sway`'s dependencies will work with it yet.  If they do, `sway` will likely use that configuration.

**Comment by lumaxis** [comment]
@whitlockjc I noticed that `json-refs` was released two weeks ago. Do you think we can pull it into Sway now?

**Comment by whitlockjc** [comment]
Yup, that's the plan.  I've just been a little busy.  I'll work on it tonight.

**Comment by lumaxis** [comment]
@whitlockjc I know the feeling 🙂 Thanks alot 🙏

**Comment by gordey4doronin** [comment]
At first glance, `sway` doesn't work with `json-refs@3.0.0`. It has dozen of failed tests.

@whitlockjc Do you have a WIP branch on upgrading `json-refs`?
I wonder if I could help with something..

```
  278 passing (9s)
  16 failing

  issues
    ✓ should trap document processing errors (Issue 16) (43ms)
(node:18611) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AssertionError: false == true
    1) should support relative references (and to YAML files) (Issue 17)
    ✓ should not throw an error for unknown formats (Issue 20) (64ms)
    ✓ should handle default and id fields (Issue 29) (61ms)
    ✓ should handle request objects that are not plain objects (Issue 35)
    ✓ should validate file parameters based on existence alone (Issue 37)
    ✓ should handle allOf $ref to a definition with circular reference (Issue 38) (62ms)
    ✓ string value for object type (Issue #46) (48ms)
    ✓ Buffer value for object type (Issue #46) (42ms)
    ✓ should handle hierchical query parameters (Issue 39) (46ms)
    ✓ should not validate optional parameters that are undefined (Issue 60) (43ms)
    ✓ should not throw an error for optional strings that are undefined (Issue 60) (42ms)
    should handle mixed-case headers for validation (Issue 67)
      ✓ parameter processing
      ✓ request validation
      ✓ response validation

  Operation
    swaggerApiRelativeRefs
      2) should handle composite parameters
      3) should handle explicit parameters
      4) should handle explicit parameters
      5) should create proper regexp (with basePath)
      ✓ should create proper regexp (with basePath ending in slash) (42ms)
      ✓ should create proper regexp (without basePath) (48ms)
      #getParameter
        ✓ should return the proper response (38ms)
      #getParameters
        6) should return the proper parameter objects
      #getSecurity
        7) should return the proper parameter objects
      #validateRequest
        validate Content-Type
          ✓ should handle global level consumes (47ms)
          ✓ should handle mime-type parameters (exact match) (41ms)
          operation level consumes
            8) should return an error for an unsupported value
            9) should handle an undefined value (defaults to application/octet-stream)
            10) should not return an error for a supported value
        validate parameters
          11) should return an error for invalid non-primitive parameters
          12) should return an error for invalid primitive parameters
          13) should not return an error for valid parameters
      #validateResponse
        14) should return the 'default' response when validating an undefined response
        should return an error for undefined response
          15) undefined value but no default
          16) provided value

```

**Comment by whitlockjc** [comment]
I don't expect it to work as-is.  `json-refs@v3.0.0` changed how circulars are identified _(for the better)_ and resolution in general.  It also removed the `options.relativeBase` option for `json-refs`.  I don't have a branch yet but I hope to work on it soon.  I was out of town for a race this weekend and just didn't get to it.

**Comment by whitlockjc** [comment]
This PR is now obsolete.

**Pull request closed without merging**
