### PR TITLE
Fix sub schemas validations from 'properties' keyword

### PR DESCRIPTION
**Pull request by IvanGoncharov**

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
Checking sub schema is not easy.
That is why I think https://github.com/zaggino/z-schema/issues/114 should be good solution for such cases. You just hook your checks to `#/definitions/schema` and z-schema do all traversal for you.

**Comment by IvanGoncharov** [comment]
@whitlockjc Hi, can you please review this PR?

**Comment by whitlockjc** [comment]
I was just building your other PR locally, give me a minute.

**Comment by whitlockjc** [comment]
Thanks.

**Pull request merged**
