### PR TITLE
Using default value for array if no default value is defined for items

### LINKED ISSUE #132: Default value for parameters with type array not taken into account
Hi,

If we define a global default value for a parameter with type array, the default value will never be used, even if no default value is set for the items.

For a parameter defined like this :
```
fields:
    name: fields
    in: query
    type: array
    items:
      type: string
    required: false
    default: ["uuid", "name", "value"]
```
if i call the api without specifying the fields parameter in the query, `request.swagger.params.fields.value` will remain `undefined`. I would expect it to be `["uuid", "name", "value"]`

I've seen in the code that you expect default values to be set in the items definitions and never fall back to the global default. It prevents me from having a default value with more than one item in it in my example.

If you agree that somehow this default value should be used, there would be 2 ways of doing it:
- check first for the presence of the global default value and use it if present. It means that the potential default values of the items would never be used.
- process the default values of the items and if the result is still undefined and if there is a global default value, use this value.

The first option would suit my needs better but i'm open to both of them.

I've coded both options on my computer so i can contribute to the project if needed. Feel free to ask me.

Regards

### PR DESCRIPTION
**Pull request by vinassefranche**
The global array's default value will only be used if there would be none without it.

If the items in the array have default values, they will still be used.

Fixes #132

### CODE REVIEW

**Comment by whitlockjc** [comment]
Thanks, I will take a peek later this week.

**Comment by whitlockjc** [comment]
Do you mind updating your commit to remove the changes to `browser/*`?  I will rebuild the files after I merge your changes.

**Comment by whitlockjc** [comment]
Does this replace #89?

**Comment by vinassefranche** [comment]
Changes has been done.
And yes it seems that it does the same job as #89 .
Thanks for looking at this!

**Comment by whitlockjc** [comment]
Thanks a lot!

**Pull request merged**
