### PR TITLE
Small cleanups

### PR DESCRIPTION
**Pull request by IvanGoncharov**
@whitlockjc Could you please review it?

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
By the way it should reduce size of browser bundles.
Since full JSON Schema was included twice.

@whitlockjc Could you please review it?

**Comment by whitlockjc** [comment]
Of course.  I'll give it a peek sometime today.

**Comment by whitlockjc** [comment]
Thanks a lot @IvanGoncharov.  When your work for #28 is done, we can create the `1.0.0` release.  How's that sound?

**Comment by IvanGoncharov** [comment]
@whitlockjc Yes that will work for me.
Thing to note is I'm only interested in validation part of #28.

**Pull request merged**
