### PR TITLE
Updated the Swagger 2.0 JSON Schema file with upstream changes

### PR DESCRIPTION
**Pull request by IvanGoncharov**
@whitlockjc I sync local version with `swagger-spec` repo.
Change was made in swagger-api/swagger-spec/pull/474

### CODE REVIEW

**Comment by IvanGoncharov** [comment]
@whitlockjc it simple fix but it significantly blocks me. Can you please merge it?

**Comment by mohsen1** [comment]
Instead of directly pasting the schema you could use [swagger-schema-official](https://www.npmjs.com/package/swagger-schema-official) package as well

**Comment by IvanGoncharov** [comment]
@mohsen1 I argee in long run it's good solution. It actually will help if this package is referenced somewhere in docs. At least in README.md of swagger-spec.
Another problem is that package doesn't keep in sync with schema inside `swagger-spec`.

**Comment by whitlockjc** [comment]
Thanks.

**Pull request merged**
