### PR TITLE
Handle Buffer bodies. Issue #103

### PR DESCRIPTION
**Pull request by coltonmorris**

### CODE REVIEW

**Comment by whitlockjc** [comment]
Do you mind adding a test that shows this works?  Also, run `gulp` or `node ./node_modules/gulp/bin/gulp.js` prior to your commit so that you include the pre-built browser binaries in the commit.

**Comment by coltonmorris** [comment]
Yes!

**Comment by coltonmorris** [comment]
From my understanding, the tests that already exist test the feature. Does it still need more?

**Comment by whitlockjc** [comment]
When I look at the existing code, I'm now failing to understand how this isn't working as designed.  When we get a value that is a `Buffer`, we will stringify it first and then handle the coercing based on the type requested.  The only way this shouldn't work is if your body parameter is not of type `object`.  Can you give me the schema for your body parameter?  _(If it is a reference, give me the referenced schema as well.)_

**Comment by coltonmorris** [comment]
The problem was the Buffer conversion was happening too late when the type is undefined. It would return a Buffer value before the conversion could happen. The changes I implemented just converted the Buffer right away.

**Comment by coltonmorris** [comment]
`  /auth/login:
    x-swagger-router-controller: auth
    post:
      tags:
        - no-auth
      operationId: login
      description: 'Given login credentials, returns a login token.'
      parameters:
        - name: bodyJson
          in: body
          description: Login credentials.
          required: true
          schema:
            allOf:
              - required:
                  - username
                properties:
                  username:
                    type: string
              - required:
                  - password
                properties:
                  password:
                    type: string
              - required:
                  - partner
                properties:
                  partner:
                    type: string
      responses:
        '200':
          description: A jwt token
          schema:
            required:
              - token
            properties:
              token:
                type: string
`

**Comment by whitlockjc** [comment]
What I'm saying is that `type` should **never** be `undefined`.

**Comment by whitlockjc** [comment]
I realize the Swagger 2.0 specification does **not** require `type` to be set but it should never be unset and most tools, like sway, will work only when `type` is set.  If it were, your Swagger above would proper work _(or should)_.

Maybe @webron can jump in and help plead your case.

**Comment by whitlockjc** [comment]
https://github.com/apigee-127/sway/issues/45

**Comment by whitlockjc** [comment]
I don't see how we can do type conversion when we don't know the requested type, that's the problem.  Sure, we can come up with some magic that might work most of the time but I don't like magic.  I _could_ fall back to `JSON.parse` for this but I'm sure it would have overhead and there would be cases where it just wouldn't work, like with non-JSON bodies.

**Comment by coltonmorris** [comment]
Yeah, #45 is pretty clear. Thanks!

**Pull request closed without merging**
